# Generated by Django 5.2.3 on 2025-06-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0028_beatmap_hitobject_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPRace",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("gamemode", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting to start"),
                            ("in_progress", "In progress"),
                            ("finished", "Finished"),
                        ]
                    ),
                ),
                ("duration", models.IntegerField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("calculator_engine", models.CharField()),
                ("primary_performance_value", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="PPRacePlayer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pp", models.FloatField()),
                ("score_count", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pprace_players",
                        to="profiles.osuuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PPRaceScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("performance_total", models.FloatField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pprace_scores",
                        to="ppraces.ppraceplayer",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pprace_scores",
                        to="profiles.score",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ppraceplayer",
            name="scores",
            field=models.ManyToManyField(
                related_name="pprace_players",
                through="ppraces.PPRaceScore",
                to="profiles.score",
            ),
        ),
        migrations.CreateModel(
            name="PPRaceTeam",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("total_pp", models.FloatField()),
                ("score_count", models.IntegerField()),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="pprace_teams",
                        through="ppraces.PPRacePlayer",
                        to="profiles.osuuser",
                    ),
                ),
                (
                    "pprace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="ppraces.pprace",
                    ),
                ),
                (
                    "scores",
                    models.ManyToManyField(
                        related_name="pprace_teams",
                        through="ppraces.PPRaceScore",
                        to="profiles.score",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ppracescore",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pprace_scores",
                to="ppraces.ppraceteam",
            ),
        ),
        migrations.AddField(
            model_name="ppraceplayer",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="ppraces.ppraceteam",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppracescore",
            constraint=models.UniqueConstraint(
                fields=("player_id", "score_id"), name="unique_pprace_score"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppraceplayer",
            constraint=models.UniqueConstraint(
                fields=("team_id", "user_id"), name="unique_pprace_player"
            ),
        ),
    ]
