# Generated by Django 5.2.3 on 2025-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppraces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pprace",
            name="status",
            field=models.CharField(
                choices=[
                    ("lobby", "Lobby"),
                    ("waiting_to_start", "Waiting to start"),
                    ("in_progress", "In progress"),
                    ("finished", "Finished"),
                ]
            ),
        ),
    ]
