# Generated by Django 5.2.3 on 2025-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppraces", "0002_alter_pprace_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ppraceteam",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="ppraceplayer",
            name="pp_contribution",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
