# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppraces", "0003_alter_ppraceteam_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pprace",
            name="pp_decay_base",
            field=models.FloatField(default=0.95),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pprace",
            name="status",
            field=models.CharField(
                choices=[
                    ("lobby", "Lobby"),
                    ("waiting_to_start", "Waiting to start"),
                    ("in_progress", "In progress"),
                    ("finalising", "Finalising"),
                    ("finished", "Finished"),
                ]
            ),
        ),
    ]
