# Generated by Django 5.2.4 on 2025-07-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppraces", "0004_pprace_pp_decay_base_alter_pprace_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pprace",
            name="duration",
        ),
    ]
