# Generated by Django 2.2 on 2019-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20190519_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="extra_pp",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_accuracy",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_ar",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_bpm",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_cs",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_length",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_od",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
