# Generated by Django 2.2 on 2019-06-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_auto_20190607_2315"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
