# Generated by Django 2.2.3 on 2019-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_auto_20190623_1834"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="score",
            name="unique_score",
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("user_stats_id", "date"), name="unique_score"
            ),
        ),
    ]
