# Generated by Django 2.2.3 on 2019-12-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_auto_20191210_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="gamemode",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
