# Generated by Django 3.0 on 2020-03-28 01:35

from django.db import migrations, models

import common.osu.enums
import profiles.enums


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_score_gamemode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_beatmap_status",
                    models.IntegerField(
                        default=profiles.enums.AllowedBeatmapStatus["RANKED_ONLY"]
                    ),
                ),
                ("oldest_beatmap_date", models.DateTimeField(blank=True, null=True)),
                ("newest_beatmap_date", models.DateTimeField(blank=True, null=True)),
                ("oldest_score_date", models.DateTimeField(blank=True, null=True)),
                ("newest_score_date", models.DateTimeField(blank=True, null=True)),
                ("lowest_ar", models.FloatField(blank=True, null=True)),
                ("highest_ar", models.FloatField(blank=True, null=True)),
                ("lowest_od", models.FloatField(blank=True, null=True)),
                ("highest_od", models.FloatField(blank=True, null=True)),
                ("lowest_cs", models.FloatField(blank=True, null=True)),
                ("highest_cs", models.FloatField(blank=True, null=True)),
                (
                    "required_mods",
                    models.IntegerField(default=common.osu.enums.BitMods["NONE"]),
                ),
                (
                    "disqualified_mods",
                    models.IntegerField(default=common.osu.enums.BitMods["NONE"]),
                ),
                ("lowest_accuracy", models.FloatField(blank=True, null=True)),
                ("highest_accuracy", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
