# Generated by Django 3.0 on 2020-06-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_scorefilter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstats",
            name="nochoke_pp",
        ),
    ]
