# Generated by Django 3.0.7 on 2020-06-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_remove_userstats_nochoke_pp"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorefilter",
            name="highest_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scorefilter",
            name="lowest_length",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
