# Generated by Django 3.2.4 on 2021-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_auto_20200615_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="scorefilter",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
