# Generated by Django 3.2.4 on 2022-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_auto_20210614_0706"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="score",
            name="profiles_sc_pp_840a93_idx",
        ),
        migrations.RenameField(
            model_name="beatmap",
            old_name="star_rating",
            new_name="difficulty_total",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="star_rating",
            new_name="difficulty_total",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="nochoke_pp",
            new_name="nochoke_performance_total",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="pp",
            new_name="performance_total",
        ),
        migrations.AddField(
            model_name="beatmap",
            name="difficulty_calculator_engine",
            field=models.CharField(default="legacy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beatmap",
            name="difficulty_calculator_version",
            field=models.CharField(default="legacy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="difficulty_calculator_engine",
            field=models.CharField(default="legacy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="difficulty_calculator_version",
            field=models.CharField(default="legacy", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["performance_total"], name="profiles_sc_perform_b4b2d6_idx"
            ),
        ),
    ]
