# Generated by Django 4.0.6 on 2022-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_auto_20220710_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beatmap",
            name="max_combo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="difficulty_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="nochoke_performance_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="result",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
