# Generated by Django 4.2.3 on 2023-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0015_alter_beatmap_max_combo_alter_score_difficulty_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="extra_pp",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_accuracy",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_ar",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_bpm",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_cs",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_length",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="score_style_od",
            field=models.FloatField(default=0),
        ),
    ]
