# Generated by Django 4.2.11 on 2024-05-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_difficultycalculation_performancecalculation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="difficultycalculation",
            name="unique_difficulty_calculation",
        ),
        migrations.RemoveConstraint(
            model_name="performancecalculation",
            name="unique_performance_calculation",
        ),
        migrations.AlterField(
            model_name="performancevalue",
            name="calculation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_values",
                to="profiles.performancecalculation",
            ),
        ),
        migrations.AddConstraint(
            model_name="difficultycalculation",
            constraint=models.UniqueConstraint(
                fields=("beatmap_id", "mods", "calculator_engine"),
                name="unique_difficulty_calculation",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancecalculation",
            constraint=models.UniqueConstraint(
                fields=("score_id", "calculator_engine"),
                name="unique_performance_calculation",
            ),
        ),
    ]
