# Generated by Django 4.2.13 on 2024-06-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0018_remove_difficultycalculation_unique_difficulty_calculation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="score",
            name="unique_score",
        ),
        migrations.AddField(
            model_name="score",
            name="mutation",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="original_score",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutations",
                to="profiles.score",
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("user_stats_id", "date", "mutation"), name="unique_score"
            ),
        ),
    ]
