# Generated by Django 4.2.13 on 2024-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_remove_score_unique_score_score_mutation_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="score",
            name="profiles_sc_perform_b4b2d6_idx",
        ),
        migrations.RemoveField(
            model_name="beatmap",
            name="difficulty_calculator_engine",
        ),
        migrations.RemoveField(
            model_name="beatmap",
            name="difficulty_calculator_version",
        ),
        migrations.RemoveField(
            model_name="beatmap",
            name="difficulty_total",
        ),
        migrations.RemoveField(
            model_name="score",
            name="difficulty_calculator_engine",
        ),
        migrations.RemoveField(
            model_name="score",
            name="difficulty_calculator_version",
        ),
        migrations.RemoveField(
            model_name="score",
            name="difficulty_total",
        ),
        migrations.RemoveField(
            model_name="score",
            name="nochoke_performance_total",
        ),
        migrations.RemoveField(
            model_name="score",
            name="performance_total",
        ),
    ]
