# Generated by Django 5.1.2 on 2024-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_remove_score_profiles_sc_perform_b4b2d6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beatmap",
            name="artist",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="beatmap",
            name="creator_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="beatmap",
            name="difficulty_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="beatmap",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="difficultycalculation",
            name="calculator_engine",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="difficultycalculation",
            name="calculator_version",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="difficultyvalue",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="osuuser",
            name="country",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="osuuser",
            name="username",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="performancecalculation",
            name="calculator_engine",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="performancecalculation",
            name="calculator_version",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="performancevalue",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="score",
            name="rank",
            field=models.CharField(),
        ),
    ]
