# Generated by Django 5.1.3 on 2024-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_alter_beatmap_artist_alter_beatmap_creator_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="is_classic",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
