# Generated by Django 5.1.3 on 2024-11-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_score_is_classic"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="statistics",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
