# Generated by Django 5.1.4 on 2024-12-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_rename_is_classic_score_is_stable"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorefilter",
            name="disqualified_mods_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scorefilter",
            name="required_mods_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
