# Generated by Django 5.2.1 on 2025-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0027_alter_scorefilter_disqualified_mods_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beatmap",
            name="hitobject_counts",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
