# Generated by Django 5.2.4 on 2025-07-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_beatmap_hitobject_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="last_updated",
            field=models.DateTimeField(),
        ),
    ]
