# Generated by Django 6.0.5 on 2026-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0029_alter_userstats_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beatmap",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
