# Generated by Django 5.1.2 on 2024-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_scorefilterpreset_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorefilterpreset",
            name="name",
            field=models.CharField(),
        ),
    ]
