# Generated by Django 6.0.5 on 2026-07-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leaderboards", "0030_alter_leaderboard_notification_settings"),
        ("profiles", "0029_alter_userstats_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField()),
                ("description", models.TextField(blank=True)),
                ("logo", models.CharField(blank=True)),
                ("theme_colours", models.JSONField(blank=True, default=dict)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("creation_time", models.DateTimeField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendees",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendees",
                        to="profiles.osuuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventAttendee",
                to="profiles.osuuser",
            ),
        ),
        migrations.CreateModel(
            name="EventLeaderboard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_leaderboards",
                        to="events.event",
                    ),
                ),
                (
                    "leaderboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_leaderboard",
                        to="leaderboards.leaderboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventOrganiser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_organisers",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_organisers",
                        to="profiles.osuuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organisers",
            field=models.ManyToManyField(
                related_name="organised_events",
                through="events.EventOrganiser",
                to="profiles.osuuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventattendee",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_attendee"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventorganiser",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_organiser"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="event_start_before_end",
            ),
        ),
    ]
