# Generated by Django 6.0.5 on 2026-07-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("profiles", "0029_alter_userstats_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatmapChallenge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField()),
                ("gamemode", models.IntegerField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("best_combo", "Best Combo"),
                            ("lowest_miss_count", "Lowest Miss Count"),
                        ]
                    ),
                ),
                (
                    "beatmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.beatmap",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beatmap_challenges",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeatmapChallengeScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.beatmapchallenge",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beatmap_challenge_scores",
                        to="profiles.score",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beatmap_challenge_scores",
                        to="profiles.osuuser",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "user"), name="unique_challenge_user"
                    )
                ],
            },
        ),
    ]
