# Generated by Django 6.0.5 on 2026-08-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_beatmapchallenge_beatmapchallengescore"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_scores", models.IntegerField()),
                ("total_regular_hits", models.BigIntegerField()),
                ("total_play_time", models.BigIntegerField()),
                ("total_pp", models.FloatField()),
                ("unique_players", models.IntegerField()),
                ("unique_countries", models.IntegerField()),
                ("unique_maps", models.IntegerField()),
                ("last_updated", models.DateTimeField()),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
