# Generated by Django 5.2.9 on 2026-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstats",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
