# Generated by Django 6.0.5 on 2026-07-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0029_alter_userstats_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Minigame",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("game_type", models.CharField()),
                ("name", models.CharField()),
                ("gamemode", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("waiting_to_start", "Waiting to start"),
                            ("in_progress", "In progress"),
                            ("finalising", "Finalising"),
                            ("finished", "Finished"),
                        ]
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField()),
                ("initial_state", models.JSONField(blank=True)),
                ("state", models.JSONField(blank=True)),
                ("state_last_computed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_free_for_all", models.BooleanField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.osuuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinigameStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("wins", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minigame_stats",
                        to="profiles.osuuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinigameTeam",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("points", models.FloatField()),
                ("score_count", models.IntegerField()),
                (
                    "minigame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="minigames.minigame",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MinigamePlayer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("points", models.FloatField()),
                ("score_count", models.IntegerField()),
                ("scores_last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minigame_players",
                        to="profiles.osuuser",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="minigames.minigameteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minigame",
            name="winning_team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_minigame",
                to="minigames.minigameteam",
            ),
        ),
        migrations.CreateModel(
            name="MinigameScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("points", models.FloatField()),
                (
                    "minigame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="minigames.minigame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="minigames.minigameplayer",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minigame_scores",
                        to="profiles.score",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="minigames.minigameteam",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "score"), name="unique_minigame_score"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="minigameplayer",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_minigame_player"
            ),
        ),
        migrations.AddIndex(
            model_name="minigame",
            index=models.Index(
                fields=["game_type"], name="minigames_m_game_ty_b23c35_idx"
            ),
        ),
    ]
