# Production overrides for compose.yaml

services:
  db:
    restart: always

  queue:
    restart: always

  cache:
    restart: always

  api:
    build:
      target: production-runner
    restart: always

  worker:
    build:
      target: production-runner
    restart: always

  worker_monitor:
    build:
      target: production-runner
    restart: always

  scheduler:
    build:
      target: production-runner
    restart: always

  prometheus:
    restart: always

  grafana:
    restart: always

  difficalcy-osu:
    restart: always

  difficalcy-cache:
    restart: always
