# Additional services for running tooling in development and CI
# Must be used with compose.yaml

services:
  tooling:
    build:
      context: .
      target: tooling
    env_file:
      - config/active/django.env
    volumes:
      - .:/app
      - beatmaps:/beatmaps
    user: ${UID}:${GID}
    depends_on:
      - db
      - queue
      - cache
      - difficalcy-osu
