# Development overrides for compose.yaml

services:
  db:
    ports:
      - 5432:5432

  api:
    build:
      target: development-runner
    volumes:
      - .:/app

  worker:
    build:
      target: development-runner
    volumes:
      - .:/app

  worker_monitor:
    build:
      target: development-runner
    volumes:
      - .:/app

  scheduler:
    build:
      target: development-runner
    volumes:
      - .:/app

  difficalcy-osu:
    ports:
      - 5000:80
    volumes:
      - ./common/osu/stubdata/beatmap_provider:/beatmaps
