# Production overrides for compose.yaml

services:
  db:
    restart: always

  queue:
    restart: always

  cache:
    restart: always

  api:
    build:
      target: production-runner
    ports:
      - 8000:8000
    restart: always

  worker:
    build:
      target: production-runner
    restart: always

  worker_monitor:
    build:
      target: production-runner
    ports:
      - 5555:5555
    restart: always

  scheduler:
    build:
      target: production-runner
    restart: always

  prometheus:
    restart: always

  grafana:
    ports:
      - 3000:3000
    restart: always

  difficalcy-osu:
    restart: always

  difficalcy-taiko:
    restart: always

  difficalcy-catch:
    restart: always

  difficalcy-mania:
    restart: always

  difficalcy-performanceplus:
    restart: always

  difficalcy-cache:
    restart: always
