# Services for running the application

volumes:
  db-data:
  queue-data:
  prometheus-data:
  grafana-data:
  beatmaps:
  cache-data:
  difficalcy-cache-data:

secrets:
  grafana_admin_password:
    file: ./config/active/secrets/grafana_admin_password

services:
  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - config/active/postgres.env
    shm_size: 128m

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    env_file:
      - config/active/postgres-exporter.env

  queue:
    image: rabbitmq:4-management
    env_file:
      - config/active/rabbitmq.env
    volumes:
      - queue-data:/var/lib/rabbitmq:rw

  cache:
    image: redis:8
    volumes:
      - cache-data:/data

  api:
    build: .
    env_file:
      - config/active/django.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - db
      - queue
      - cache
      - difficalcy-osu
      - difficalcy-taiko
      - difficalcy-catch
      - difficalcy-mania
      - difficalcy-performanceplus

  worker:
    build: .
    command: celery --app osuchan worker --loglevel info
    healthcheck:
      test: celery --app osuchan inspect ping || exit 1
    env_file:
      - config/active/django.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - db
      - queue
      - difficalcy-osu
      - difficalcy-taiko
      - difficalcy-catch
      - difficalcy-mania
      - difficalcy-performanceplus

  worker_monitor:
    build: .
    command: celery --app osuchan flower
    env_file:
      - config/active/django.env
      - config/active/flower.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - worker

  scheduler:
    build: .
    command: celery --app osuchan beat --loglevel info --schedule /tmp/celerybeat-schedule
    env_file:
      - config/active/django.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - queue

  prometheus:
    image: prom/prometheus:v3.7.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus:rw

  grafana:
    image: grafana/grafana:12.2.1
    env_file:
      - ./config/active/grafana.env
    volumes:
      - grafana-data:/var/lib/grafana:rw
    secrets:
      - grafana_admin_password

  difficalcy-osu:
    image: ghcr.io/syriiin/difficalcy-osu:v0.15.0
    env_file:
      - config/active/difficalcy.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - difficalcy-cache

  difficalcy-taiko:
    image: ghcr.io/syriiin/difficalcy-taiko:v0.15.0
    env_file:
      - config/active/difficalcy.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - difficalcy-cache

  difficalcy-catch:
    image: ghcr.io/syriiin/difficalcy-catch:v0.15.0
    env_file:
      - config/active/difficalcy.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - difficalcy-cache

  difficalcy-mania:
    image: ghcr.io/syriiin/difficalcy-mania:v0.15.0
    env_file:
      - config/active/difficalcy.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - difficalcy-cache

  difficalcy-performanceplus:
    image: ghcr.io/syriiin/difficalcy-performanceplus:v0.12.0
    env_file:
      - config/active/difficalcy.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - difficalcy-cache

  difficalcy-cache:
    image: redis:8
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/active/difficalcy-redis.conf:/usr/local/etc/redis/redis.conf
      - difficalcy-cache-data:/data
