# Development overrides for compose.yaml

services:
  db:
    ports:
      - 5432:5432

  api:
    build:
      target: development-runner
    volumes:
      - .:/app

  worker:
    build:
      target: development-runner
    command: watchmedo auto-restart --pattern=*.py --recursive -- celery --app osuchan worker --loglevel info
    volumes:
      - .:/app

  worker_monitor:
    build:
      target: development-runner
    volumes:
      - .:/app

  scheduler:
    build:
      target: development-runner
    command: watchmedo auto-restart --pattern=*.py --recursive -- celery --app osuchan beat --loglevel info --schedule /tmp/celerybeat-schedule
    volumes:
      - .:/app

  difficalcy-osu:
    ports:
      - 6000:80
    volumes:
      - ./common/osu/stubdata/beatmap_provider:/beatmaps

  difficalcy-taiko:
    ports:
      - 6001:80
    volumes:
      - ./common/osu/stubdata/beatmap_provider:/beatmaps

  difficalcy-catch:
    ports:
      - 6002:80
    volumes:
      - ./common/osu/stubdata/beatmap_provider:/beatmaps

  difficalcy-mania:
    ports:
      - 6003:80
    volumes:
      - ./common/osu/stubdata/beatmap_provider:/beatmaps
