# Services for running the application

volumes:
  queue-data:
  prometheus-data:
  grafana-data:
  beatmaps:
  redis-data:

secrets:
  grafana_admin_password:
    file: ./config/active/secrets/grafana_admin_password

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - config/active/postgres.env
    shm_size: 128m

  queue:
    image: rabbitmq:3-management
    env_file:
      - config/active/rabbitmq.env
    volumes:
      - queue-data:/var/lib/rabbitmq:rw

  cache:
    image: memcached:1

  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - config/active/django.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - db
      - queue
      - cache
      - difficalcy-osu

  worker:
    build: .
    command: celery --app osuchan worker --loglevel info
    env_file:
      - config/active/django.env
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - db
      - queue
      - difficalcy-osu

  worker_monitor:
    build: .
    command: celery --app osuchan flower
    ports:
      - 5555:5555
    env_file:
      - config/active/django.env
      - config/active/flower.env
    depends_on:
      - worker

  scheduler:
    build: .
    command: celery --app osuchan beat --loglevel info --schedule /tmp/celerybeat-schedule
    env_file:
      - config/active/django.env
    depends_on:
      - queue

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus:rw

  grafana:
    image: grafana/grafana:10.0.2
    ports:
      - 3001:3000
    env_file:
      - ./config/active/grafana.env
    volumes:
      - grafana-data:/var/lib/grafana:rw
    secrets:
      - grafana_admin_password

  difficalcy-osu:
    image: ghcr.io/syriiin/difficalcy-osu:v0.7.0
    env_file:
      - config/active/difficalcy-osu.env
    environment:
      - REDIS_CONFIGURATION=redis:6379
    volumes:
      - beatmaps:/beatmaps
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
