# Additional services for running tooling in development and CI
# Must be used with docker-compose.yml

services:
  tooling:
    build:
      context: .
      target: development-tooling
    env_file:
      - config/active/django.env
    volumes:
      - .:/app
      - ./data/beatmaps:/app/beatmaps
    user: ${UID}:${GID}
    depends_on:
      - db
      - queue
      - cache
