# Production overrides for docker-compose.yml

services:
  api:
    build:
      target: production-runner

  worker:
    build:
      target: production-runner

  worker_monitor:
    build:
      target: production-runner

  scheduler:
    build:
      target: production-runner
