# Additional services for running tooling in development and CI
# Must be used with docker-compose.yml

services:
  tooling:
    build:
      context: .
      target: development-tooling
    env_file:
      - django.env
    volumes:
      - .:/app
    user: ${UID}:${GID}
    depends_on:
      - db    # required for eg. makemigrations
