groups:
  - name: django_request_latency
    interval: 1m
    rules:
      - record: view:django_http_requests_latency:p50
        expr: histogram_quantile(0.50, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m]))) > 0

      - record: view:django_http_requests_latency:p95
        expr: histogram_quantile(0.95, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m]))) > 0

      - record: view:django_http_requests_latency:p99
        expr: histogram_quantile(0.99, sum by (le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m]))) > 0

      - record: view:django_http_requests:rate
        expr: sum by (view) (rate(django_http_requests_total_by_view_transport_method_total[5m]))
