global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000

  - job_name: queue
    metrics_path: /metrics/per-object
    static_configs:
      - targets:
          - queue:15692

  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets:
          - postgres-exporter:9187
