[tool.poetry]
name = "osuchan-backend"
version = "0.1.0"
description = ""
authors = ["Samuel Cattini-Schultz <syriiins@gmail.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.2.7"
Django = "^4.0.6"
djangorestframework = "^3.12.4"
django-debug-toolbar = "^3.2.1"
gunicorn = "^20.1.0"
httpx = "^0.23.0"
oppaipy = "^1.0.4"
psycopg2-binary = "^2.9.1"
pymemcache = "^3.5.0"
requests = "^2.25.1"
rosu-pp-py = "^0.9.3"
tqdm = "^4.64.0"
flower = "^1.1.0"
pydantic = "^1.10.7"

[tool.poetry.group.dev.dependencies]
black = "^22.6.0"
isort = "^5.9.3"
coverage = {extras = ["toml"], version = "^7.2.6"}
pytest = "^7.3.1"
pytest-django = "^4.5.2"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "osuchan.settings"

[tool.coverage.run]
source = ["."]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
