# Generated by Django 2.2 on 2019-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osuauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_beta_tester",
            field=models.BooleanField(default=False),
        ),
    ]
