# Generated by Django 3.0 on 2020-06-08 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_userstats_nochoke_pp'),
        ('osuauth', '0003_auto_20190718_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreFilterPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ScoreFilter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
