# Generated by Django 3.0.7 on 2020-06-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osuauth', '0004_scorefilterpreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreFilterPreset',
        ),
    ]
