# Generated by Django 3.2.4 on 2021-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osuauth", "0005_delete_scorefilterpreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
