# Generated by Django 4.0.6 on 2022-07-23 09:21

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def set_last_active(apps, schema_editor):
    User = apps.get_model("osuauth", "User")

    User.objects.update(last_active=F("last_login"))


class Migration(migrations.Migration):
    dependencies = [
        ("osuauth", "0006_auto_20210614_0706"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_last_active, migrations.RunPython.noop),
    ]
