#!/bin/bash
set -euo pipefail

if [ -z "${1+x}" ]; then
    echo -e "Missing restore input path.\neg. scripts/restoredb ~/backups/osuchan.dump"
    exit 1
fi

docker-compose exec -T db dropdb \
    --username=osuchan \
    osuchan

echo "Database dropped"

docker-compose exec -T db createdb \
    --username=osuchan \
    --template=template0 \
    osuchan

echo "Database created"

docker-compose exec -T db pg_restore \
    --username=osuchan \
    --dbname=osuchan \
    --format=custom \
    --exit-on-error \
    --verbose \
    < $1

echo "Database restored"
