#!/bin/bash
set -euo pipefail

if [ -z "${1+x}" ]; then
    echo -e "Missing restore input path.\neg. scripts/restoredb ~/backups/osuchan.dump"
    exit 1
fi

docker-compose exec -T db pg_restore \
    --username=osuchan \
    --dbname=osuchan \
    --format=custom \
    --clean \
    --verbose \
    < $1
