# Generated by Django 2.2 on 2019-06-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0005_auto_20190623_1834"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gamemode", models.IntegerField()),
                ("visibility", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("allow_past_scores", models.BooleanField()),
                ("allowed_beatmap_status", models.IntegerField()),
                ("oldest_beatmap_date", models.DateTimeField(blank=True, null=True)),
                ("newest_beatmap_date", models.DateTimeField(blank=True, null=True)),
                ("lowest_ar", models.FloatField(blank=True, null=True)),
                ("highest_ar", models.FloatField(blank=True, null=True)),
                ("lowest_od", models.FloatField(blank=True, null=True)),
                ("highest_od", models.FloatField(blank=True, null=True)),
                ("lowest_cs", models.FloatField(blank=True, null=True)),
                ("highest_cs", models.FloatField(blank=True, null=True)),
                ("required_mods", models.IntegerField()),
                ("disqualified_mods", models.IntegerField()),
                ("lowest_accuracy", models.FloatField(blank=True, null=True)),
                ("highest_accuracy", models.FloatField(blank=True, null=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pp", models.FloatField()),
                ("join_date", models.DateTimeField(auto_now_add=True)),
                (
                    "leaderboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="leaderboards.Leaderboard",
                    ),
                ),
                ("scores", models.ManyToManyField(to="profiles.Score")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="profiles.OsuUser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="members",
            field=models.ManyToManyField(
                related_name="leaderboards",
                through="leaderboards.Membership",
                to="profiles.OsuUser",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_leaderboards",
                to="profiles.OsuUser",
            ),
        ),
    ]
