# Generated by Django 2.2 on 2019-07-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_auto_20190623_1834"),
        ("leaderboards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboard",
            old_name="visibility",
            new_name="access_type",
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("invite_date", models.DateTimeField(auto_now_add=True)),
                (
                    "leaderboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="leaderboards.Leaderboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="profiles.OsuUser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="invitees",
            field=models.ManyToManyField(
                related_name="invited_leaderboards",
                through="leaderboards.Invite",
                to="profiles.OsuUser",
            ),
        ),
    ]
