# Generated by Django 2.2.3 on 2019-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0005_auto_20190718_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="newest_score_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="oldest_score_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
