# Generated by Django 3.0 on 2020-03-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_scorefilter"),
        ("leaderboards", "0006_auto_20190721_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="score_filter",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.ScoreFilter",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="allow_past_scores",
            field=models.BooleanField(default=True),
        ),
    ]
