# Generated by Django 3.0 on 2020-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0010_auto_20200331_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='score_set',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
