# Generated by Django 3.2.4 on 2021-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0014_leaderboard_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
