# Generated by Django 4.2.11 on 2024-05-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0018_remove_difficultycalculation_unique_difficulty_calculation_and_more",
        ),
        ("leaderboards", "0017_alter_leaderboard_member_count"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE leaderboards_membership_scores RENAME TO leaderboards_membershipscore",
                    reverse_sql="ALTER TABLE leaderboards_membershipscore RENAME TO leaderboards_membership_scores",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="MembershipScore",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        (
                            "membership",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="membership_scores",
                                to="leaderboards.membership",
                            ),
                        ),
                        (
                            "score",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="membership_scores",
                                to="profiles.score",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="membership",
                    name="scores",
                    field=models.ManyToManyField(
                        through="leaderboards.MembershipScore", to="profiles.score"
                    ),
                ),
            ],
        )
    ]
