# Generated by Django 4.2.11 on 2024-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0018_membershipscore_alter_membership_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipscore",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
