# Generated by Django 4.2.11 on 2024-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0019_alter_membershipscore_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipscore",
            name="performance_total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="membershipscore",
            index=models.Index(
                fields=["performance_total"], name="leaderboard_perform_0a0217_idx"
            ),
        ),
    ]
