# Generated by Django 4.2.11 on 2024-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0020_membershipscore_performance_total_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("leaderboard_id", "user_id"), name="unique_memberships"
            ),
        ),
    ]
