# Generated by Django 4.2.13 on 2024-08-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leaderboards",
            "0023_leaderboard_scores_membershipscore_leaderboard_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="calculator_engine",
            field=models.CharField(default="osu.Game.Rulesets.Osu", max_length=50),
            preserve_default=False,
        ),
    ]
