# Generated by Django 4.2.13 on 2024-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0024_leaderboard_calculator_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="primary_performance_value",
            field=models.CharField(default="total", max_length=20),
            preserve_default=False,
        ),
    ]
