# Generated by Django 5.1.2 on 2024-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0025_leaderboard_primary_performance_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="calculator_engine",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="icon_url",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="notification_discord_webhook_url",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="primary_performance_value",
            field=models.CharField(),
        ),
    ]
