# Generated by Django 5.2.1 on 2025-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0026_alter_leaderboard_calculator_engine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="custom_colours",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
