# Generated by Django 6.0.3 on 2026-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0027_leaderboard_custom_colours"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="is_event",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
