# Generated by Django 6.0.4 on 2026-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0028_leaderboard_is_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="notification_settings",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
