# Generated by Django 6.0.4 on 2026-04-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0029_leaderboard_notification_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="notification_settings",
            field=models.JSONField(blank=True),
        ),
    ]
