# Generated by Django 6.1 on 2026-09-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0030_alter_leaderboard_notification_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="top_scores",
            field=models.JSONField(blank=True, default=list),
            preserve_default=False,
        ),
    ]
